abspath = pwd;
addpath(strcat(abspath,'/NUDG/Codes1D'))
addpath(strcat(abspath,'/NUDG/Codes2D'))
addpath(strcat(abspath,'/NUDG/Codes2Dquad'))
addpath(strcat(abspath,'/NUDG/Codes3D'))
addpath(strcat(abspath,'/NUDG/ServiceRoutines'))
addpath(strcat(abspath,'/NUDG/CFD1D'))
addpath(strcat(abspath,'/NUDG/CFD2D'))
addpath(strcat(abspath,'/NUDG/Grid/'))
addpath(strcat(abspath,'/NUDG/Grid/CFD'))
addpath(strcat(abspath,'/NUDG/Grid/3D'))
addpath(strcat(abspath,'/NUDG/Grid/CNS2D'))
addpath(strcat(abspath,'/NUDG/Grid/Euler2D'))
addpath(strcat(abspath,'/NUDG/Grid/Maxwell2D'))
addpath(strcat(abspath,'/NUDG/Grid/Other'))
addpath(strcat(abspath,'/DG-inceuler'))
addpath(strcat(abspath,'/DG-inceuler/localdivproj'))
